# Generated by Django 5.1.15 on 2026-09-25 14:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('root_namespace', models.CharField(help_text='Root CID namespace (e.g. cisce.icse.chemistry).', max_length=512, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9]*(\\.[a-z][a-z0-9]*){2,}$', 'Namespace must be lowercase dot-separated (e.g. cisce.icse.chemistry.redox).')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(db_index=True, help_text='Fully-qualified CID namespace.', max_length=768, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9]*(\\.[a-z][a-z0-9]*){2,}$', 'Namespace must be lowercase dot-separated (e.g. cisce.icse.chemistry.redox).')])),
                ('label', models.CharField(max_length=256)),
                ('summary', models.TextField(blank=True, help_text='One-paragraph plain-English explanation.')),
                ('cognitive_state', models.CharField(choices=[('unknown', 'Unknown'), ('broken', 'Broken'), ('repaired', 'Repaired'), ('mastered', 'Mastered')], db_index=True, default='unknown', max_length=16)),
                ('depth', models.PositiveSmallIntegerField(default=0, help_text='Topological depth from the root goal node (0 = root).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.goal')),
            ],
            options={
                'ordering': ['depth', 'namespace'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('requires', 'Requires'), ('supports', 'Supports')], default='requires', max_length=16)),
                ('weight', models.FloatField(default=1.0, help_text='Dependency strength (0-1).')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_edges', to='core.conceptnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_edges', to='core.conceptnode')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='core.goal')),
            ],
            options={
                'ordering': ['source__depth'],
                'constraints': [models.UniqueConstraint(fields=('goal', 'source', 'target'), name='unique_goal_edge')],
            },
        ),
        migrations.AddConstraint(
            model_name='conceptnode',
            constraint=models.UniqueConstraint(fields=('goal', 'namespace'), name='unique_goal_namespace'),
        ),
    ]
